# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret "my_proxy"
  ip_ban_enabled: true
  login_attempts_threshold: 3
  
# Text to speech
tts:
  - platform: google_translate
    
group: !include groups.yaml
automation: !include automations.yaml
#automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
#camera: !include cameras.yaml
sensor: !include sensors.yaml
#climate: !include climate.yaml
switch: !include switches.yaml
recorder: !include recorder.yaml
mqtt: !include mqtt.yaml
template: !include templates.yaml


influxdb:
  host: !secret "influx_host"
  port: !secret "influx_port"
  database: homeassistant
  username: !secret influx1_usr
  password: !secret influx1_pwd
  max_retries: 9
  default_measurement: state

device_tracker: !include device_tracker.yaml

logger:
  default: info
  logs:
    homeassistant.components.onvif: info
#    custom_components.my_integration: critical

stream:
api:

#alexa:
#  smart_home:
#    locale: en-US
#    endpoint: https://api.amazonalexa.com/v3/events
#    client_id: https://pitangui.amazon.com/
#    client_secret: F1772AA678574BACB0AC3106DCAA2CA0

#    filter:
#      include_entities:
#        - light.greg_s_light
#        - light.living_room_light
#        - light.theresas_light
#        - light.kitchen_sink_light
#        - light.bathroom_night_light
#        - light.deck_light
#        - light.deck_stair_lights
#        - light.post_light
#      include_entity_globs:
#        - binary_sensor.*_motion
#      include_domains:
#        - switch
#      exclude_entities:
#        - switch.outside
#      exclude_domains:
#        - binary_sensor.*
#        - camera.*
#        - button.*
#        - device_tracker.*
#        - sensor.*
#    entity_config:
#      light.greg_s_light:
#        name: "Greg's Light"
#        description: "The light next to Greg"
#      light.theresas_light:
#        name: "Theresa's Light"
#        description: "The light next to Theresa"
#      light.living_room_light:
#          name: "Living Room Fan Light"
#          description: "Light in living room fan"
#      switch.stairs:
#        display_categories: LIGHT

emulated_hue:
  host_ip: 192.168.8.20
#  listen_port: 8300
  listen_port: 80
#  advertise_ip: 10.0.0.10
#  advertise_port: 8080
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false
  exposed_domains:
#    - light
#    - switch
  entities:
    light.greg_s_light_2:
      name: "Greg's Light"
    light.living_room_fan:
      name: "Living Room Fan Light"
      hidden: false
    light.theresas_light_3:
      name: "Theresa's Light"
      hidden: false
    light.deck_light:
      name: "Deck Light"
      hidden: false
    fan.living_room_fan:
      name: "Living Room Fan"
      hidden: false
    light.kitchen_sink_light:
      name: "Kitchen Sink Light"
      hidden: false


shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
