# - 433 Mhz Arduino Sensors Disabled 02/03/2021
sensor:
  - name: "Beer Fridge Temp"
    state_topic: "rtl_433home/Ambientweather-F007TH/27/7"
    unit_of_measurement: "°F"
    value_template: "{{ value_json.temperature_F }}"
    force_update: true
    unique_id: 17651EA7E9FB46D2


  - name: "Beer Fridge Battery"
    state_topic: "rtl_433home/Ambientweather-F007TH/27/7"
    value_template: "{{ value_json.battery_ok }}"
    force_update: true
    unique_id: 92CFAED178694D19


  - name: "Main Fridge Temp"
    state_topic: "rtl_433home/Ambientweather-F007TH/0/8"
    unit_of_measurement: "°F"
    value_template: "{{ value_json.temperature_F }}"
    force_update: true
    unique_id: 74F9ECE916D548CA


  - name: "Main Fridge Battery"
    state_topic: "rtl_433home/Ambientweather-F007TH/0/8"
    unit_of_measurement: "°F"
    value_template: "{{ value_json.battery_ok }}"
    force_update: true
    unique_id: 1B411E8B071C440F


  - name: "Breeze Pro Temp"
    state_topic: "rtl_433home/LaCrosse-BreezePro/694658"
    unit_of_measurement: "°F"
    value_template: "{{ value_json.temperature_F }}"
    force_update: true
    payload_available: "online"
    payload_not_available: "offline"
    unique_id: 41CA5C2ED5344676


  - name: "Breeze Pro Humidity"
    state_topic: "rtl_433home/LaCrosse-BreezePro/694658"
    unit_of_measurement: "%"
    value_template: "{{ value_json.humidity }}"
    force_update: true
    payload_available: "online"
    payload_not_available: "offline"
    unique_id: C871AF0D2B614F3E


  - name: "Breeze Pro Wind Speed"
    state_topic: "rtl_433home/LaCrosse-BreezePro/694658"
    unit_of_measurement: "mph"
    value_template: "{{ value_json.wind_avg_mi_h | round(1) }}"
    force_update: true  
    payload_available: "online"
    payload_not_available: "offline"
    unique_id: 270ACE67A4E04805


  - name: "Breeze Pro Wind Dir"
    state_topic: "rtl_433home/LaCrosse-BreezePro/694658"
    unit_of_measurement: "deg"
    value_template: "{{ value_json.wind_dir_deg }}"
    force_update: true 
    payload_available: "online"
    payload_not_available: "offline"
    unique_id: 96FF51CCD0CE402C


#  - state_topic: "home/Front_Porch"
#    name: "Front Porch Temp"
#    unit_of_measurement: "°F"
#    value_template: "{{ value_json.temp }}"

#  - state_topic: "home/Front_Porch"
#    name: "Front Porch Humidity"
#    unit_of_measurement: "%"
#    value_template: "{{ value_json.humid }}"

#  - state_topic: "home/Living_Room"
#    name: "2nd Floor Temp"
#    unit_of_measurement: "°F"
#    value_template: "{{ value_json.temp }}"

#  - state_topic: "home/Living_Room"
#    name: "2nd Floor Humidity"
#    unit_of_measurement: "%"
#    value_template: "{{ value_json.humid }}"

#  - state_topic: "home/Plant_Room"
#    name: "Plant_Room_Temp"
#    unit_of_measurement: "°F"
#    value_template: "{{ value_json.temp }}"


#  - state_topic: "home/Office"
#    name: "Office_Humidity"
#    unit_of_measurement: "%"
#    value_template: "{{ value_json.humid }}"

#  - state_topic: "appliances/Basement_Fridge"
#    name: "Basement_Fridge_Temp"
#    unit_of_measurement: "°F"
#    value_template: "{{ value_json.temp }}"


#  - state_topic: "hydroponic/tank/weight"
#    name: "Inside Tank Volume"
#    unit_of_measurement: "Gal"
#    value_template: "{{ value_json.weight}}"

#  - state_topic: "hydroponic/tank/temp"
#    name: "Inside Tank Temp"
#    unit_of_measurement: "°F"
#    value_template: "{{ value_json.temp}}"

#  - state_topic: "outTopic"
#    name: "Arduino Out"

#  - state_topic: "inTopic"
#    name: "Arduino In"
