esphome:
  name: climate-office

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Climate-Office Fallback Hotspot"
    password: !secret "fallback_password"

captive_portal:

#dallas:
#  - pin: D1
  
sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "Office Temp "
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"        
    humidity:
      name: "Office Humidity"
    model: AM2302
    update_interval: 60s
    #Actual Measurememts
    # calibrate linear
    #- 24.6 -> 22.3
    
