esphome:
  name: dryer_sensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dryer Sensor Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

api:
  encryption:
    key: !secret api_key
    

ota:
  password: !secret ota_orig_password

sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Dryer Current"
    update_interval: 30s
    accuracy_decimals: 2
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 4.0A
          # Value shown in logs: 0.1333A
          - 0.07 -> 25.2

  # Example source sensor
  - platform: adc
    pin: A0
    id: adc_sensor
    update_interval: 30s 
    accuracy_decimals: 4
    unit_of_measurement: Vac
    
 # - platform: pulse_counter
#    pin: D6
#    update_interval: 30s
#    unit_of_measurement: 'kW'
#    name: 'Dryer KW'
#    filters:
#      - multiply: 0.06  # (60s/1000 pulses per kWh)    