esphome:
  name: grow_bed
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "PhoneHome"
  password: "Married042503"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Grow Bed Fallback Hotspot"
    password: !secret "Fallback_password"
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "419Erie"

ota:
  password: "419Erie"

## Enables Left (CCW) Pump on GPIO14 L_EN
switch:
  - platform: gpio
    pin: D7
    name: "Nutrient Tank Pump"
    restore_mode: RESTORE_DEFAULT_ON


## L_PWM GPI15 Pin D8
output:
  - platform: esp8266_pwm
    pin: D6
    frequency: 50 Hz    
    id: pwm_output

light:
  - platform: monochromatic
    output: pwm_output
    name: "Pump Speed"   

sensor:
  #flow meter east D6 gpio12
  - platform: pulse_counter
    pin: TX
    name: "East Flowrate"
    unit_of_measurement: 'lph'
    accuracy_decimals: 2
    filters:
#      - multiply: 0.0318
      - multiply: .002235

# flow meter center D7 gpio 13
  - platform: pulse_counter
    pin: D4
    name: "Center Flowrate"
    unit_of_measurement: 'lph'
    accuracy_decimals: 2
    filters:
#      - multiply: 0.0318
      - multiply: .002235
     
  #flow meter east D8 gpio15
  - platform: pulse_counter
    pin: D5
    name: "West Flowrate"
    unit_of_measurement: 'lph'
    accuracy_decimals: 2
    filters:
#      - multiply: 0.0318  
      - multiply: .002235      