esphome:
  name: hydroponics-outside
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret hydroponics-outside_ota_password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hydroponics-Outside"
    password: !secret fallback_password

captive_portal:


dallas:
  - pin: D2

status_led:
  pin:
    number: D4
    inverted: False

sensor:
  - platform: dallas
    address: 0x2D3C01D075031A28
    accuracy_decimals: 1
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"  
    name: "Outside Tank Temp"

  - platform: hx711
    name: "Outside Tank Volume"
    dout_pin: D0
    clk_pin: D1
    gain: 128
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      - calibrate_linear:
          - 106656 -> 0
          - 400000 -> 5
          - 770000 -> 10
          - 1072000 -> 15
          - 1381500 -> 20
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
    unit_of_measurement: gal
 
# flow meter center D6 gpio 12
  - platform: pulse_counter
    pin: D6
    name: "Outside East Channel Flow"
    unit_of_measurement: 'lpm'
    update_interval: 30s
    accuracy_decimals: 2
    filters:
#      - multiply: 0.0318
      - multiply: .002235
     
  #flow meter east D7 gpio13
  - platform: pulse_counter
    pin: D7
    name: "Outside West Channel Flow"
    unit_of_measurement: 'lpm'
    update_interval: 30s
    accuracy_decimals: 2
    filters:
#      - multiply: 0.0318  
      - multiply: .002235  