esphome:
  name: hydroponic_sensors
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hydroponic-Sensors"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_orig_password

i2c:
  sda: D2
  scl: D3
  scan: True
  id: bus_a
  
sensor:
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
    green_channel:
      name: "TCS34725 Green Channel"
    blue_channel:
      name: "TCS34725 Blue Channel"
    clear_channel:
      name: "TCS34725 Clear Channel"
    illuminance:
      name: "TCS34725 Illuminance"
    color_temperature:
      name: "TCS34725 Color Temperature"
    gain: 1x
    integration_time: 2.4ms
    address: 0x29
    update_interval: 60s
  - platform: dht
    pin: D7
    model: AM2302
    temperature:
      name: "Grow Bed Temp AM2302"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"        
    humidity:
      name: "Grow Bed Humidity"
      unit_of_measurement: "%"
    update_interval: 60s   

switch:
  - platform: gpio
    name: "LED"
    pin:
      number: D6
      inverted: no