esphome:
  name: patio-sensors

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_orig_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Patio-Sensors Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

#dallas:
#  - pin: D1
  
sensor:
  - platform: dht
    model: AM2302
    pin: D2
    temperature:
      name: "Patio Temp AM2302"
      filters:
    #  - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          #- 14.8 -> -13.8
          #- 23.7 -> 18
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"        
    humidity:
      name: "Patio Humidity"
      filters:
 #     - calibrate_linear:
 #         - 89.0 -> 99
    update_interval: 60s
    
  - platform: resistance
    sensor: photo_sensor
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Patio Light Sensor
    unit_of_measurement: "Ω"

# Example source sensor:
  - platform: adc
    id: photo_sensor
    pin: A0
    update_interval: 60s
    
#  - platform: dallas
#    address: 0x4C3C01D6079C5C28
#    filters:
#    - lambda: return x * (9.0/5.0) + 32.0;
#    unit_of_measurement: "°F"      
#    name: "Patio Temp"     