esphome:
  name: washer-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
    
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Washer Sensor Fallback Hotspot"
    password: !secret fallback_password

captive_portal:
    
sensor:
  - platform: ct_clamp
    sensor: adc_sensor_washer
    name: "Washer Current"
    unit_of_measurement: A
    update_interval: 500ms
    accuracy_decimals: 2
    filters:
 #     - calibrate_linear:
          # Measured value of 0 maps to 0A
#          - 0.53220 -> 0.03
#          # Known load: 4.0A
#          # Value shown in logs: 0.1333A
#          - 0.53418 -> 0.4
#          - 0.54297 -> 0.25
 #         - 0.83887 -> 3.98


  # Example source sensor
  - platform: adc
    pin: A0
    id: adc_sensor_washer
    #filters:
    # - multiply: 3.3
#    raw: true
#    update_interval: 0.5s
#    accuracy_decimals: 6
#    unit_of_measurement: V
    
    
    