esphome:
  name: weather_office
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather Office Fallback Hotspot"
    password: "0lqpgiuYqhZq"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
#  password: !secret api_password
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_orig_password


#dallas:
#  - pin: D1
  
sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "Office Temp "
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"        
    humidity:
      name: "Office Humidity"
    update_interval: 60s
    #Actual Measurememts
    # calibrate linear
    #- 24.6 -> 22.3
    
#  - platform: resistance
#    sensor: photo_sensor
#    configuration: DOWNSTREAM
#    resistor: 10kOhm
#    name: Patio Light Sensor

# Example source sensor:
#  - platform: adc
#    id: photo_sensor
#    pin: A0
#    update_interval: 60s
    
#  - platform: dallas
#    address: 0x933C01D60760DA28
#    filters:
#    - lambda: return x * (9.0/5.0) + 32.0;
#    unit_of_measurement: "°F"      
#    name: "Office Temp"    
    