esphome:
  name: climate-first-floor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Climate First Floor"
    password: !secret "fallback_password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password

dallas:
  - pin: D1

sensor:
  - platform: dht
    pin: D2
    temperature:
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"  
      name: "1st Floor Temp"
    humidity:
      unit_of_measurement: "%"
      name: "1st Floor Humidity"
    update_interval: 60s
    model: AM2302

  - platform: resistance
    sensor: photo_sensor1
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: "Living Room Light Sensor"
    unit_of_measurement: "Ω"

  - platform: dallas
    address: 0xce3c01d6077a8c28
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"  
    name: "Living Room Radiator Temp"

# Example source sensor:
  - platform: adc
    id: photo_sensor1
    pin: A0
    update_interval: 10s